/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiRegisterRouteImport } from './routes/api/register'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api/public/feedback'
import { Route as ApiPublicMessagesRouteImport } from './routes/api/public/messages'
import { Route as ApiPublicRegisterRouteImport } from './routes/api/public/register'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegisterRoute = ApiRegisterRouteImport.update({
  id: '/api/register',
  path: '/api/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMessagesRoute = ApiPublicMessagesRouteImport.update({
  id: '/api/public/messages',
  path: '/api/public/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRegisterRoute = ApiPublicRegisterRouteImport.update({
  id: '/api/public/register',
  path: '/api/public/register',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/register': typeof ApiRegisterRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/messages': typeof ApiPublicMessagesRoute
  '/api/public/register': typeof ApiPublicRegisterRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/register'
    | '/api/public/feedback'
    | '/api/public/messages'
    | '/api/public/register'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/register'
    | '/api/public/feedback'
    | '/api/public/messages'
    | '/api/public/register'
  id:
    | '__root__'
    | '/'
    | '/api/register'
    | '/api/public/feedback'
    | '/api/public/messages'
    | '/api/public/register'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiRegisterRoute: typeof ApiRegisterRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicMessagesRoute: typeof ApiPublicMessagesRoute
  ApiPublicRegisterRoute: typeof ApiPublicRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/register': {
      id: '/api/register'
      path: '/api/register'
      fullPath: '/api/register'
      preLoaderRoute: typeof ApiRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/messages': {
      id: '/api/public/messages'
      path: '/api/public/messages'
      fullPath: '/api/public/messages'
      preLoaderRoute: typeof ApiPublicMessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/register': {
      id: '/api/public/register'
      path: '/api/public/register'
      fullPath: '/api/public/register'
      preLoaderRoute: typeof ApiPublicRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiRegisterRoute: ApiRegisterRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicMessagesRoute: ApiPublicMessagesRoute,
  ApiPublicRegisterRoute: ApiPublicRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
